/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.9.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as backfillRequestors from "../backfillRequestors.js";
import type * as http from "../http.js";
import type * as redirectToPrs from "../redirectToPrs.js";
import type * as releasePrs from "../releasePrs.js";
import type * as vesta from "../vesta.js";
import type * as webhook from "../webhook.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  backfillRequestors: typeof backfillRequestors;
  http: typeof http;
  redirectToPrs: typeof redirectToPrs;
  releasePrs: typeof releasePrs;
  vesta: typeof vesta;
  webhook: typeof webhook;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
